name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
    CI:
        name: CI
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1 
        - name: yarn install
          run: yarn
        - name: Run eslint
          run: yarn lint
        - name: Run Jest
          run: yarn test
        - name: Upload test coverage artifact
          uses: actions/upload-artifact@v1
          with:
            name: coverage
            path: coverage
        - name: Show coverage in comments
          uses: ziishaned/jest-reporter-action@v0.0.1
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            test-command: "yarn test-coverage"